### ISSUE TITLE
添加专栏修改的功能，完善专栏

### ISSUE THREAD

**Issue by yanyan0925** [onlyfun2023/onlyfun#2]
让专栏可以修改封面图，名称，收费数量和币种
添加邀请功能，例如专栏主可以免费邀请某人加入，成员可以邀请其他onlyfun用户加入
专栏主可以设置邀请奖励，例如成员邀请其他人加入，给10%佣金等

**Comment by maiyude2018** [comment]
让专栏可以修改封面图，名称，收费数量和币种  **(原创建圈子接口可实现)**

添加邀请功能，例如专栏主可以免费邀请某人加入，成员可以邀请其他onlyfun用户加入 （待添加）

专栏主可以设置邀请奖励，例如成员邀请其他人加入，给10%佣金等 （待添加）
