### ISSUE TITLE
发文小bug

### ISSUE THREAD

**Issue by hanzheruofeng** [onlyfun2023/onlyfun#27]
如果用户设置了仅自己可发文，别人再发文会出现如下提示：
![QMN_T E2 4ZC(O4~DPEW4MH](https://user-images.githubusercontent.com/130156669/230698804-4dc3ab71-7a14-4210-bfe9-91d21c1293d4.png)
上面显示“发文失败，请重新发文”，于是用户会觉得是自己的问题，多次发文，但是不然，是圈主的设置原因。

**Comment by maiyude2018** [comment]
考虑更改提示语
