### ISSUE TITLE
页面自动跳转问题

### ISSUE THREAD

**Issue by hanzheruofeng** [onlyfun2023/onlyfun#29]
问题重现：显示页面在首页，点击我的，在我的页面停留1到2秒又自动跳转到首页，从下图1就变成图2，图2中蓝色条在我的，但是显示在主页。
注：以上情况只有部分时候出现，有时候点击正常，有时候错误。
![C6OY6A)CLB@V{PK40 0~O@7](https://user-images.githubusercontent.com/130156669/230755531-944599dd-7656-4d5b-ad33-54a321ca10b2.png)
![)4RQX)$}2DHW4BU9ZMY(K1B](https://user-images.githubusercontent.com/130156669/230755532-f1a940f4-e871-42c9-99e1-c45f58f24684.png)

**Comment by maiyude2018** [comment]
已记录，准备增加防抖和节流
