### ISSUE TITLE
点击 复制邀请链接 后得到的链接中 invitedld中的l应改为i

### ISSUE THREAD

**Issue by coonehub** [onlyfun2023/onlyfun#44]
![0](https://user-images.githubusercontent.com/130625643/231648104-022df5e8-44c0-4dfa-a1cd-df679adbbd89.png)
![1](https://user-images.githubusercontent.com/130625643/231648151-ab97f469-a5c6-460a-a8d8-e8dd04d6be6a.png)

**Comment by maiyude2018** [comment]
那是大写的I
