### ISSUE TITLE
关于无法搜索专栏的问题

### ISSUE THREAD

**Issue by MOYI2** [onlyfun2023/onlyfun#52]
名字相近的专栏，短名无法搜索的bug
eg:搜索帽子的专栏“冲”，但由于平台有名称为“冲冲冲”的专栏，便无法搜索出来帽子的专栏，只会显示“冲冲冲”这个专栏。

**Comment by maiyude2018** [comment]
可以正常显示的，不能显示是因为圈主设置了隐藏
