### ISSUE TITLE
“View on Blockbrowser” 跳转后的页面 是乱码  (ID：qb488d7e9)

### ISSUE THREAD

**Issue by coonehub** [onlyfun2023/onlyfun#61]
![1](https://user-images.githubusercontent.com/130625643/236607973-7dcc333c-45cf-4720-8586-b2539bd47cce.png)
![2](https://user-images.githubusercontent.com/130625643/236607983-0a481d83-6786-47c4-adab-b3491835bbf7.png)
![3](https://user-images.githubusercontent.com/130625643/236607993-55dd9a40-b5ea-44ff-80b3-6d7ca2501edb.png)

ID：qb488d7e9

**Comment by maiyude2018** [comment]
信息都是加密后上链的。链上信息是乱码属于正常
